name: Update Ratings

on:
  schedule:
    # every 14 days
    - cron: "0 15 3 * *"

  # can be triggered manually
  workflow_dispatch:

jobs:
  update_ratings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Use Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - name: Run tests
        run: devenv shell run_tests

      - name: Run update_reviews
        run: devenv shell update_reviews

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: update data.yaml via update_reviews.py
