name: Update Readme and Map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Ratings"]
    branches: [main]
    types:
      - completed

jobs:
  update_readme_and_map:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Use Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - name: Run tests
        run: devenv shell run_tests

      - name: Run create_readme
        run: devenv shell create_readme

      - name: Run create_map_data
        run: devenv shell create_map_data

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: update readme.md via create_readme.py
